### ISSUE TITLE
Erro no link do repo

### ISSUE THREAD

**Issue by Creuma-Kuzola** [lucasfront/lucasfront.github.io#1]
Olá, Lucas!
Espero que esteja tudo bem com você!
Estava a ver mais sobre o seu repositório , tentei acessar o link da página desse mesmo repo e apareceu um erro! 
Dizendo que a o link não foi encontrado!

**Comment by lucasfront** [comment]
Olá, muito obrigado pelo aviso, eu havia mudado o domínio e não me atentei em alterar. obrigado.

**Comment by Creuma-Kuzola** [comment]
De nada, Lucas!
